# Generated by Django 2.2.6 on 2019-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
