# Generated by Django 2.2.6 on 2019-10-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0002_auto_20191025_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
