# Generated by Django 2.2.6 on 2019-10-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0004_component_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gluck.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='new page', max_length=300),
        ),
    ]
