# Generated by Django 2.2.6 on 2019-10-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0008_auto_20191027_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Text',
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ImageField(upload_to='')),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gluck.Page')),
            ],
        ),
    ]
