# Generated by Django 2.2.6 on 2019-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0011_auto_20191027_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
