# Generated by Django 2.2.6 on 2019-10-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0012_auto_20191027_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='page',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
