# Generated by Django 2.2.6 on 2019-10-29 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0013_auto_20191029_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
