# Generated by Django 2.2.6 on 2019-10-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0014_auto_20191029_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Component'},
        ),
    ]
