# Generated by Django 2.2.6 on 2019-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0016_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
