# Generated by Django 2.2.6 on 2019-11-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0017_auto_20191101_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
